### ISSUE TITLE
Version 0.13 messes with pypi 

### ISSUE THREAD

**Issue by Poddster** [irskep/sphinx-better-theme#32]
The instructions from the readme:

    pip install sphinx-better-theme

result in version 0.13 being installed. To get the latest release it would need to be:

    pip install sphinx-better-theme==0.1.5

This is because pip thinks 0.13.0 is a bigger number than 0.1.x, and there are a few using this format:

https://pypi.python.org/simple/sphinx-better-theme/

To avoid people having to specify I guess you could remove the old versions from pypi and 'rebrand' them as 0.1.3, 0.1.2 etc?

**Comment by irskep** [comment]
THANK YOU for reporting this! I'll see what I can do.

**Comment by irskep** [comment]
I've removed the offending versions. I can't believe I didn't realize this before. You're the best!

**Comment by Poddster** [comment]
Thanks for fixing it!

I only noticed because I was using a local version of it, which I had modified. Then I moved my modifications to my own 'theme' that extended yours from pypi and wondered why everything had changed! (In 1.13 the sidebar had more css specifiers and so "won" against my overloaded versions).

And thanks for making it. All my changes were in the css, except for a tiny overload of the header, as I wanted the logo in there rather than in the sidebar.

**Comment by irskep** [comment]
What's your project? I can link to it from the docs.

**Comment by deoren** [comment]
@Poddster Apologies to jump in on this thread, but quick question for @irskep :

How would you like documentation projects that use this theme to let you know about it?

@Poddster Thanks for reporting this.

**Comment by irskep** [comment]
Open a PR adding yourself to `docs/index.rst` :-)

**Comment by deoren** [comment]
@irskep Thanks!
@Poddster Sorry for the intrusion!
