### ISSUE TITLE
PyPI releases missing?

### ISSUE THREAD

**Issue by jezdez** [irskep/sphinx-better-theme#34]
Hi @irskep,

I just had a few CI builds fail since I believe you removed the 0.13 release from PyPI?

I see the tags for 0.11, 0.12 and 0.13 are still in this repo, so I assume it was just a cleanup, but I wanted to confirm nevertheless.

Thanks!

**Comment by irskep** [comment]
I removed the PyPI versions for 0.11-0.13 because they did not follow semver and were messing up new installs. What errors are you getting?

**Comment by jezdez** [comment]
@irskep No issues per se, just that I pinned the 0.13 version a while ago since it was the latest one at the time of adding it in our requirements.txt file and when our CI system ran the tests with that it failed because it couldn't find the release. Just wanted to confirm that I'm not imagining things :)

Closing the issue since you answered the question. Thanks for the theme by the way!
