### ISSUE TITLE
hint admonition not styled

### ISSUE THREAD

**Issue by dvarrazzo** [irskep/sphinx-better-theme#37]
The `hint` directive (an [admonition type](https://docutils.sourceforge.io/docs/ref/rst/directives.html#specific-admonitions)) doesn't have a style associated.

https://github.com/psycopg/psycopg3/blob/d066658bd30dbbe56127875a0e682da84e854845/docs/usage.rst#L161-L167

Proposal:
```css
.hint {
  background: #ffc;
  border: 1px solid #dda;
}
```

Which [looks like this](https://www.psycopg.org/psycopg3/docs/usage.html#transaction-management):

![image](https://user-images.githubusercontent.com/199429/99602034-9bf3b380-29f8-11eb-93c8-6d910aa2eaf5.png)

**Comment by irskep** [comment]
Works for me. Real talk, though, I don't pay any attention to this anymore so you'll have to open a PR for it to get done, andI'll have to see if I can even access my PyPI account still to do a release. :-)

**Comment by dvarrazzo** [comment]
Is there a better package to use to make Sphinx usable on mobile, which is currently maintained?

**Comment by irskep** [comment]
I don't know, I no longer use Sphinx for anything. :-)
